Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# Offense count: 1
Lint/Debugger:
  Exclude:
    - 'features/step_definitions/debug_steps.rb'


Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Exclude:
    - 'features/step_definitions/debug_steps.rb'

Metrics/LineLength:
  Max: 124

Metrics/PerceivedComplexity:
  Exclude:
    - 'features/support/lib/extensions/pry_if.rb'

Style/CaseEquality:
  Exclude:
    - 'features/support/lib/extensions/pry_if.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'features/support/lib/extensions/pry_if.rb'