Metrics/LineLength:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - 'lib/appium_accessors.rb'
    - 'lib/appium_controls.rb'

Lint/IneffectiveAccessModifier:
  Exclude:
    - 'lib/extensions/guidewire_form_text_controls.rb'
    - 'lib/extensions/guidewire_forms.rb'
    - 'lib/extensions/guidewire_questions.rb'

Lint/RescueException:
  Enabled: false

Lint/ShadowedArgument:
  Exclude:
    - 'lib/extensions/hookable_accessors.rb'
Lint/UnderscorePrefixedVariableName:
  Exclude:
    - 'lib/extensions/guidewire_accessors.rb'
    - 'lib/extensions/guidewire_form_text_controls.rb'
Lint/UselessAssignment:
  Exclude:
    - 'lib/extensions/hookable_accessors.rb'
Naming/AccessorMethodName:
  Exclude:
    - 'lib/helpers/browser.rb'
Style/GlobalVars:
  Exclude:
    - 'lib/helpers/mobile_helper.rb'
Style/MixinUsage:
  Exclude:
    - 'bin/console.rb'
Style/GuardClause:
  Exclude:
    - 'lib/extensions/data_magic_extensions.rb'
Style/Documentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 16
  Exclude:
    - 'lib/extensions/guidewire_accessors.rb'
    - 'lib/extensions/hookable_accessors.rb'
    - 'lib/extensions/data_magic_extensions.rb'
    - 'lib/extensions/page_object_extensions.rb'
    - 'lib/appium*.*'
    - 'lib/pages/base*.*'
    - 'lib/helpers/hook_helper.rb'

Metrics/MethodLength:
  Max: 29

Metrics/ModuleLength:
  Max: 325

Metrics/PerceivedComplexity:
  Max: 10

Style/EvalWithLocation:
  Exclude:
    - 'lib/extensions/hookable_accessors.rb'
    - 'lib/extensions/section_parents.rb'

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'lib/extensions/guidewire_questions.rb'
    - 'lib/helpers/sms_helper.rb'

