version: '2'
services:
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
    links:
      - hub
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952

  firefox:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
    links:
      - hub
