version: '2'
services:
  selenium_hub:
    image: selenium/hub
    ports:
      - 4444:4444
    environment:
      - GRID_TIMEOUT=120000
      - GRID_BROWSER_TIMEOUT=120000
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium_hub
    ports:
      - 5900
    environment:
      - no_proxy=localhost
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - selenium_hub
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952

  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium_hub
    ports:
      - 5900
    environment:
      - no_proxy=localhost
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - selenium_hub
